version: "3"

services:
  nuxt_brand:
    build: ./
    container_name: nuxt
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WEBSITE=brand
    command:
      "npm run start"

  nuxt_family:
    build: ./
    container_name: nuxt
    restart: always
    ports:
      - "3000:3000"
    environment:
      - WEBSITE=family
    command:
      "npm run start"

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt