version: "3"

services:
  nuxt:
    build: ./
    container_name: nuxt
    restart: always
    ports:
      - "3000:3000"
    volumes:
     - ./app/lang/jsons:/src/lang/jsons
    command:
      "npm run start"

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt