version: "3"

services:
  nuxt_brand:
    build: 
      context: ./
      args:
        WEBSITE_MODE: brand
    container_name: nuxt_brand
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./brand.env:/.env
    env_file:
      - brand.env
    command:
      "npm run start"

  nuxt_family:
    build: 
      context: ./
      args:
        WEBSITE_MODE: family
    container_name: nuxt_family
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./family.env:/.env
    env_file:
      - family.env
    command:
      "npm run start"

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - nuxt_brand
      - nuxt_family